name: Continuous Integration

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        kernel:
        - "5.17"
        - "5.19"
        - "6.0"
        - "6.1"
    name: "Linux ${{ matrix.kernel }}"
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install libelf-dev bc
    - name: Download kernel sources
      run: |
        echo https://cdn.kernel.org/pub/linux/kernel/$(echo ${{ matrix.kernel }} | sed -E 's/([^.]+)[.].*/v\1.x/')/linux-${{ matrix.kernel }}.tar.xz
        curl https://cdn.kernel.org/pub/linux/kernel/$(echo ${{ matrix.kernel }} | sed -E 's/([^.]+)[.].*/v\1.x/')/linux-${{ matrix.kernel }}.tar.xz | tar xJ
    - name: Configure kernel sources
      run: |
        cp /boot/config-$(uname -r) linux-${{ matrix.kernel }}/.config
        yes "" | make -C linux-${{ matrix.kernel }} oldconfig
        make -C linux-${{ matrix.kernel }} modules_prepare
    - name: Build
      run: |
        make KSRC=linux-${{ matrix.kernel }}
